######################################################################
# Automatically generated by qmake (3.1) Wed Nov 4 09:25:44 2020
######################################################################

TEMPLATE = app
TARGET = layout
INCLUDEPATH += .

# Input
HEADERS += ui_mainwindow.h layout/layout/mainwindow.h /ui_mainwindow.h
FORMS += layout/layout/mainwindow.ui
SOURCES += layout.c layout/layout/main.cpp layout/layout/mainwindow.cpp
